simulator-inf: simulator-inf.c
	gcc -o simulator-inf simulator-inf.c

simulator-fin: simulator-fin.c
	gcc -o simulator-fin simulator-fin.c 

des: des.c
	gcc -o des des.c

clean: 
	$(RM) des simulator-inf simulator-fin
